<?php

/**
 * @file
 * Contains iol.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function iol_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the iol module.
    case 'help.page.iol':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('IllustratiOnLine Project Module') . '</p>';
      return $output;

    default:
  }
}
